[package]
name = "algorithms-and-data-structure-ucsandiego"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "fibo"
path = "src/fiboancci.rs"

[[bin]]
name = "lastdigit"
path = "src/lastdigit.rs"

[[bin]]
name = "fibomod"
path = "src/fibonaccimod.rs"
